name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "deployment/backend/**"
jobs:
  deploy:
    name: PyTorch Lightning API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - working-directory: deployment/backend
        run: flyctl deploy --remote-only --dockerfile Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 -a aggru-check
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
